### ISSUE TITLE
Not all settings are applied when using popout

### ISSUE THREAD

**Issue by parvusdomus** [SalieriC/SWADE-Spices-Flavours#34]
Some settings like sheet background color, hover and selectd tab colour (the ones I have seen so far) are not applied when you pop out the character, item or other sheet. On the other hand background image is applied.

**Comment by SalieriC** [comment]
This is a compatibility problem with other modules (PopOut! in this case). So technically you're not reporting a bug but you request a compatibility with another module. We can't create compatibility with every module for obvious reasons of course. That said, chances are I'll look into that and see what we can do about it (if it can be fixed) as I use PopOut! myself. Would be likely much easier if this would be a core feature though. And in my book there is no reason to have deselct as a core feature but not PopOut!. :-S
Anyway, maybe it's also a PopOut! bug rather than a compatibility problem. Need some research. Don't expect it to be solved swiftly though. :-(

**Comment by SalieriC** [comment]
@parvusdomus You could really help me by setting up a full list of things that work/don't work on the pop out. I already have a suspicion but I need to confirm it.

**Comment by SalieriC** [comment]
This is mostly a [PopOut! issue](https://github.com/League-of-Foundry-Developers/fvtt-module-popout/issues/38). We can't really create a compatibility for that in Spices & Flavours unfortunately. We need to wait for them to either give us hooks or to inherit our variables.

**Comment by SalieriC** [comment]
Seems to be fixed by PopOut!
