### ISSUE TITLE
Sheet sound on chat messages

### ISSUE THREAD

**Issue by smoothingplane** [SalieriC/SWADE-Spices-Flavours#42]
Hi, when I use ammunition management and spices & flavours, and I use a reloadable weapon, both when I shoot or reload the sheet sound is heard, moreover when reloading the sound is double.

P.S.
even with DF Logger the sound is heard when someone logging. even if I don't know it's a spices & flavours problem.

**Comment by SalieriC** [comment]
The problem is that the hook I use to execute the sound is also called whenever a sheet is merely updated. I had great help from the following people and I will work on that bug. It was indeed known when I released it and said so in the release notes. I probably shouldn't have published it as is, I am sorry for any inconvenience.

**Comment by SalieriC** [comment]
@all-contributors please add @Ethaks for example

**Comment by SalieriC** [comment]
@all-contributors please add @eclarke12 for example
