### ISSUE TITLE
Display token image instead of character image.

### ISSUE THREAD

**Issue by SalieriC** [SalieriC/SWADE-Spices-Flavours#9]
When the portrait option is toggled, display the token image instead of the character image as non-square character images don't work very well. It also doubles as a preview of the token image.

**Comment by javierriveracastro** [comment]
Should be done. Now the token portrait option is a combo box instead of a check, with possible values None, Token, Actor.

There is risk that I have forgotten some combination (I have actor with tokens in the screen, actor without tokens in the screen) but maybe some one can break it. Hope it doesn't.
